### ISSUE TITLE
Officeonline not working on NC 24 Dashboard

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/officeonline#299]
Click on a file from Recommended files. Getting spinning circle nothing happens 

![image](https://user-images.githubusercontent.com/59488153/165153626-bc993dee-b127-4ca2-9869-82ea65a7cfd1.png)

## Server details

**Operating system**:
Ubuntu 20.04
**Web server:**
Apache2
**Database:**
Mysql
**PHP version:**
8.0
**Nextcloud version:**
24.0.0 RC1
**Version of the officeonline app**
1.1.3
**Version of Office Online server**
16.0.10385.20001

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
NA
```

#### Browser log
```
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
Tt @ globals.js:62
get @ globals.js:93
_getFile @ merged-template-prepend.js?v=223543ad-101:55
getIconUrl @ merged-template-prepend.js?v=223543ad-101:98
data @ RecommendedFile.vue:90
(anonymous) @ vue.runtime.esm.js:4761
(anonymous) @ vue.runtime.esm.js:4718
gn @ vue.runtime.esm.js:4655
e._init @ vue.runtime.esm.js:5020
i @ vue.runtime.esm.js:5168
(anonymous) @ vue.runtime.esm.js:3304
init @ vue.runtime.esm.js:3133
(anonymous) @ vue.runtime.esm.js:6022
A @ vue.runtime.esm.js:5969
f @ vue.runtime.esm.js:6097
A @ vue.runtime.esm.js:5998
y @ vue.runtime.esm.js:6150
(anonymous) @ vue.runtime.esm.js:6277
w @ vue.runtime.esm.js:6363
(anonymous) @ vue.runtime.esm.js:6237
w @ vue.runtime.esm.js:6363
(anonymous) @ vue.runtime.esm.js:6526
e._update @ vue.runtime.esm.js:3963
r @ vue.runtime.esm.js:4081
pn.get @ vue.runtime.esm.js:4495
pn.run @ vue.runtime.esm.js:4570
An @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
Ve @ vue.runtime.esm.js:1915
Promise.then (async)
$e @ vue.runtime.esm.js:1942
nt @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
pn.update @ vue.runtime.esm.js:4560
ue.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
recommendedFiles @ store.js:48
(anonymous) @ vuex.esm.js:844
(anonymous) @ vuex.esm.js:466
(anonymous) @ vuex.esm.js:465
u._withCommit @ vuex.esm.js:624
u.commit @ vuex.esm.js:464
commit @ vuex.esm.js:409
(anonymous) @ store.js:82
l @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
l @ dashboard.js?v=223543ad-101:7
i @ dashboard.js?v=223543ad-101:7
Promise.then (async)
l @ dashboard.js?v=223543ad-101:7
i @ dashboard.js?v=223543ad-101:7
(anonymous) @ dashboard.js?v=223543ad-101:7
(anonymous) @ dashboard.js?v=223543ad-101:7
fetchRecommendations @ store.js:73
(anonymous) @ vuex.esm.js:851
u.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
(anonymous) @ dashboard.js:33
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ dashboard.js?v=223543ad-101:1
ConsoleLogger.js:33 [INFO] viewer: Opening viewer for file  {app: 'viewer', uid: 'axheli', path: '/New Document.docx'}
Viewer.vue:443 TypeError: Cannot read properties of undefined (reading 'theme')
    at Viewer.vue:386:1
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at Wa (Download.vue?b226:19:33)
    at a (Download.vue?b226:19:33)
(anonymous) @ Viewer.vue:443
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
Promise.then (async)
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
openFile @ Viewer.vue:344
file @ Viewer.vue:256
We @ vue.runtime.esm.js:1863
bn.run @ vue.runtime.esm.js:4584
An @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
et @ vue.runtime.esm.js:1915
Promise.then (async)
Ke @ vue.runtime.esm.js:1942
it @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
bn.update @ vue.runtime.esm.js:4560
de.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
value @ Viewer.js:183
navigate @ RecommendedFile.vue:142
click @ RecommendedFile.vue?879d:21
Ye @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
s._wrapper @ vue.runtime.esm.js:6961
ConsoleLogger.js:33 [INFO] viewer: Opening viewer for file  {app: 'viewer', uid: 'axheli', path: '/New Document.docx'}
Viewer.vue:443 TypeError: Cannot read properties of undefined (reading 'theme')
    at Viewer.vue:386:1
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at Wa (Download.vue?b226:19:33)
    at a (Download.vue?b226:19:33)
(anonymous) @ Viewer.vue:443
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
Promise.then (async)
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
openFile @ Viewer.vue:344
file @ Viewer.vue:256
We @ vue.runtime.esm.js:1863
bn.run @ vue.runtime.esm.js:4584
An @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
et @ vue.runtime.esm.js:1915
Promise.then (async)
Ke @ vue.runtime.esm.js:1942
it @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
bn.update @ vue.runtime.esm.js:4560
de.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
value @ Viewer.js:183
navigate @ RecommendedFile.vue:142
click @ RecommendedFile.vue?879d:21
Ye @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
s._wrapper @ vue.runtime.esm.js:6961
ConsoleLogger.js:33 [INFO] viewer: Opening viewer for file  {app: 'viewer', uid: 'axheli', path: '/New Document.docx'}
Viewer.vue:443 TypeError: Cannot read properties of undefined (reading 'theme')
    at Viewer.vue:386:1
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at Wa (Download.vue?b226:19:33)
    at a (Download.vue?b226:19:33)
(anonymous) @ Viewer.vue:443
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
Promise.then (async)
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
openFile @ Viewer.vue:344
file @ Viewer.vue:256
We @ vue.runtime.esm.js:1863
bn.run @ vue.runtime.esm.js:4584
An @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
et @ vue.runtime.esm.js:1915
Promise.then (async)
Ke @ vue.runtime.esm.js:1942
it @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
bn.update @ vue.runtime.esm.js:4560
de.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
value @ Viewer.js:183
navigate @ RecommendedFile.vue:142
click @ RecommendedFile.vue?879d:21
Ye @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
s._wrapper @ vue.runtime.esm.js:6961
ConsoleLogger.js:33 [INFO] viewer: Opening viewer for file  {app: 'viewer', uid: 'axheli', path: '/New Document.docx'}
Viewer.vue:443 TypeError: Cannot read properties of undefined (reading 'theme')
    at Viewer.vue:386:1
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at Wa (Download.vue?b226:19:33)
    at a (Download.vue?b226:19:33)
(anonymous) @ Viewer.vue:443
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
Promise.then (async)
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
openFile @ Viewer.vue:344
file @ Viewer.vue:256
We @ vue.runtime.esm.js:1863
bn.run @ vue.runtime.esm.js:4584
An @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
et @ vue.runtime.esm.js:1915
Promise.then (async)
Ke @ vue.runtime.esm.js:1942
it @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
bn.update @ vue.runtime.esm.js:4560
de.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
value @ Viewer.js:183
navigate @ RecommendedFile.vue:142
click @ RecommendedFile.vue?879d:21
Ye @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
s._wrapper @ vue.runtime.esm.js:6961
ConsoleLogger.js:33 [INFO] viewer: Opening viewer for file  {app: 'viewer', uid: 'axheli', path: '/New Document.docx'}
Viewer.vue:443 TypeError: Cannot read properties of undefined (reading 'theme')
    at Viewer.vue:386:1
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at Wa (Download.vue?b226:19:33)
    at a (Download.vue?b226:19:33)
(anonymous) @ Viewer.vue:443
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
Promise.then (async)
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
openFile @ Viewer.vue:344
file @ Viewer.vue:256
We @ vue.runtime.esm.js:1863
bn.run @ vue.runtime.esm.js:4584
An @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
et @ vue.runtime.esm.js:1915
Promise.then (async)
Ke @ vue.runtime.esm.js:1942
it @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
bn.update @ vue.runtime.esm.js:4560
de.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
value @ Viewer.js:183
navigate @ RecommendedFile.vue:142
click @ RecommendedFile.vue?879d:21
Ye @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
s._wrapper @ vue.runtime.esm.js:6961
ConsoleLogger.js:33 [INFO] viewer: Opening viewer for file  {app: 'viewer', uid: 'axheli', path: '/New Document.docx'}
Viewer.vue:443 TypeError: Cannot read properties of undefined (reading 'theme')
    at Viewer.vue:386:1
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at Wa (Download.vue?b226:19:33)
    at a (Download.vue?b226:19:33)
(anonymous) @ Viewer.vue:443
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
Promise.then (async)
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
openFile @ Viewer.vue:344
file @ Viewer.vue:256
We @ vue.runtime.esm.js:1863
bn.run @ vue.runtime.esm.js:4584
An @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
et @ vue.runtime.esm.js:1915
Promise.then (async)
Ke @ vue.runtime.esm.js:1942
it @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
bn.update @ vue.runtime.esm.js:4560
de.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
value @ Viewer.js:183
navigate @ RecommendedFile.vue:142
click @ RecommendedFile.vue?879d:21
Ye @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
s._wrapper @ vue.runtime.esm.js:6961
ConsoleLogger.js:33 [INFO] viewer: Opening viewer for file  {app: 'viewer', uid: 'axheli', path: '/New Document.docx'}
Viewer.vue:443 TypeError: Cannot read properties of undefined (reading 'theme')
    at Viewer.vue:386:1
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at Wa (Download.vue?b226:19:33)
    at a (Download.vue?b226:19:33)
(anonymous) @ Viewer.vue:443
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
Promise.then (async)
Wa @ Download.vue?b226:19
a @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
(anonymous) @ Download.vue?b226:19
openFile @ Viewer.vue:344
file @ Viewer.vue:256
We @ vue.runtime.esm.js:1863
bn.run @ vue.runtime.esm.js:4584
An @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
et @ vue.runtime.esm.js:1915
Promise.then (async)
Ke @ vue.runtime.esm.js:1942
it @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
bn.update @ vue.runtime.esm.js:4560
de.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
value @ Viewer.js:183
navigate @ RecommendedFile.vue:142
click @ RecommendedFile.vue?879d:21
Ye @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
s._wrapper @ vue.runtime.esm.js:6961
```

</details>

**Comment by andyxheli** [comment]
Hi @juliushaertl I know your support busy especially with NC 25 coming out soon. I just wanted to see if you might have some free time to look into this. As the moment this app is not usable with NC 24

**Comment by andyxheli** [comment]
I see that onlyoffice had the same issue with NC 24 and this is the way they fixed it 

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/pull/637/files#

**Comment by andyxheli** [comment]
Closing this so we can work on Support for NC 24 & 25 #349 for both issues
