### ISSUE TITLE
npm ci error

### ISSUE THREAD

**Issue by wmeneses** [nextcloud/officeonline#505]
Hi, I would like to test this plugin, the OOS server is ok, but when I run npm ci, it returns this errori

nternal/modules/cjs/loader.js:638
    throw err;
    ^
......

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.20 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deasync@0.1.20 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by rexrat-github** [comment]
Stuck into this as well

`npm run dev

> officeonline@2.0.3 dev /mnt/www_data/cloud/nextcloud/apps/officeonline
> NODE_ENV=development webpack --progress --config webpack.js

/mnt/www_data/cloud/nextcloud/apps/officeonline/node_modules/stylelint-webpack-plugin/node_modules/jest-worker/build/index.js:110
  _ending;
         ^

SyntaxError: Unexpected token ;
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/mnt/www_data/cloud/nextcloud/apps/officeonline/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:242:18)
    at Module._compile (/mnt/www_data/cloud/nextcloud/apps/officeonline/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/mnt/www_data/cloud/nextcloud/apps/officeonline/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/mnt/www_data/cloud/nextcloud/apps/officeonline/node_modules/stylelint-webpack-plugin/dist/getStylelint.js:9:5)
    at Module._compile (/mnt/www_data/cloud/nextcloud/apps/officeonline/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/mnt/www_data/cloud/nextcloud/apps/officeonline/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/mnt/www_data/cloud/nextcloud/apps/officeonline/node_modules/stylelint-webpack-plugin/dist/linter.js:13:22)
    at Module._compile (/mnt/www_data/cloud/nextcloud/apps/officeonline/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/mnt/www_data/cloud/nextcloud/apps/officeonline/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/mnt/www_data/cloud/nextcloud/apps/officeonline/node_modules/stylelint-webpack-plugin/dist/index.js:20:16)
    at Module._compile (/mnt/www_data/cloud/nextcloud/apps/officeonline/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! officeonline@2.0.3 dev: `NODE_ENV=development webpack --progress --config webpack.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the officeonline@2.0.3 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-02-08T18_22_17_515Z-debug.log
`

**Comment by juliusknorr** [comment]
This should be solved in the meantime as we brought the frontend dependencies up to date again.
