### ISSUE TITLE
Exception Could not find urlsrc in WOPI putRelativeFile failed when saving to ZIP via ONLYOFFICE.

### ISSUE THREAD

**Issue by igwyd** [nextcloud/officeonline#589]
**Describe the bug**
Error when saving as ZIP via ONLYOFFICE

**To Reproduce**
1. Open any DOCX file with ONLYOFFICE
2. Click on File - Save Copy As - JPG (this will save as ZIP)
3. Go to NextCloud - Administration settings - Logging
4. See error: Exception Could not find urlsrc in WOPI putRelativeFile failed, but result file anyway put in the NextCloud storage with name ```New File.zip```

**Expected behavior**
No errors in the log. 
Do you have some kind of whitelist of extensions?

**Screenshots**
![screen](https://github.com/user-attachments/assets/55e098bc-1a6b-4f3f-b623-355f47f5ba02)

**Client details:**
 - Windows 11
 - Browser chrome
 - Version 128
 - Device: desktop

## Server details

**Operating system**: Ubuntu 22.04

**Web server:** apache2

**Database:** SQLite

**PHP version:** PHP 8.2.22

**Nextcloud version:** 29.0.6 deb in docker

**Version of the officeonline app** 2.2.1

**Version of Office Online server** ONLYOFFICE-Docs 8.1.3 docker

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"p6V2TnRqGa5tt7qhjwnJ","level":3,"time":"2024-09-11T05:54:26+00:00","remoteAddr":"172.17.0.1","user":"admin","app":"officeonline","method":"POST","url":"/index.php/apps/officeonline/wopi/files/1916_oc6rc8kxmtwa?access_token=zqKYBqMEL2NboYjd4KyLPYtGDNgsg0Mr","message":"putRelativeFile failed","userAgent":"Node.js/6.13","version":"29.0.4.1","exception":{"Exception":"Exception","Message":"Could not find urlsrc in WOPI","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/officeonline/lib/TokenManager.php","line":208,"function":"getUrlSrcForFile","class":"OCA\\Officeonline\\WOPI\\Parser","type":"->","args":[["OC\\Files\\Node\\File"],true]},{"file":"/var/www/html/custom_apps/officeonline/lib/Controller/WopiController.php","line":835,"function":"getToken","class":"OCA\\Officeonline\\TokenManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"postFile","class":"OCA\\Officeonli...Controller"],"postFile"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Officeonline\\Controller\\WopiController"],"postFile"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Officeonline\\Controller\\WopiController","postFile",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["1916_oc6rc8kxmtwa","officeonline.wopi.postfile"]]},{"file":"/var/www/html/lib/base.php","line":1050,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/officeonline/wopi/files/1916_oc6rc8kxmtwa"]},{"file":"/var/www/html/index.php","line":49,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/officeonline/lib/WOPI/Parser.php","Line":213,"message":"putRelativeFile failed","CustomMessage":"putRelativeFile failed"},"id":"66e130966e0a4"}

[officeonline] Error: putRelativeFile failed
	POST /index.php/apps/officeonline/wopi/files/1916_oc6rc8kxmtwa?access_token=zqKYBqMEL2NboYjd4KyLPYtGDNgsg0Mr
	from 172.17.0.1 by admin at Sep 11, 2024, 10:54:26 AM
```

#### Browser log
```
nope
```

#### ONLYOFFICE Log
```
[2024-09-11T05:54:26.831] [ERROR] [localhost] [1916_oc6rc8kxmtwa] [userId] nodeJS - wopi error putRelativeFile:Error: Error response: statusCode:500; headers:{"date":"Wed, 11 Sep 2024 05:54:26 GMT","server":"Apache/2.4.61 (Debian)","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-robots-tag":"noindex, nofollow","x-xss-protection":"1; mode=block","x-powered-by":"PHP/8.2.22","set-cookie":["oc6rc8kxmtwa=a2fa48099d3100281378e4456fd3da50; path=/; HttpOnly; SameSite=Lax","oc_sessionPassphrase=c5af18VJzaeSY%2Bz8bleLQkz6vfNf2weQvax%2FaNQ%2B2GAbSpWoiFRv6Du2uIwZ6TfZOsf0BSLMyW3gk1dk27S5YWPWGwsPSxb8dNX7RxYkNQfswjFesXiB2fZY8xR8501q; path=/; HttpOnly; SameSite=Lax","oc6rc8kxmtwa=a2fa48099d3100281378e4456fd3da50; path=/; HttpOnly; SameSite=Lax","nc_sameSiteCookielax=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","nc_sameSiteCookiestrict=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict","oc6rc8kxmtwa=a2fa48099d3100281378e4456fd3da50; path=/; HttpOnly; SameSite=Lax","oc6rc8kxmtwa=a2fa48099d3100281378e4456fd3da50; path=/; HttpOnly; SameSite=Lax"],"content-security-policy":"default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'","x-request-id":"p6V2TnRqGa5tt7qhjwnJ","cache-control":"no-cache, no-store, must-revalidate","feature-policy":"autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'","content-length":"2","connection":"close","content-type":"application/json; charset=utf-8"}; body:
[]
    at Request._callback (/snapshot/server/Common/sources/utils.js)
    at Request.self.callback (/snapshot/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/snapshot/server/Common/node_modules/request/request.js:1161:10)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/snapshot/server/Common/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

</details>

**Comment by juliusknorr** [comment]
The extensions are provided by the office server through the /hosting/discovery endpoint, so more something on the onlyoffice from my perspective.
